- 👋 Olá,me chamo Marcus Barbosa,Tenho 20 anos e moro em Salvador-BA
- 👀 Estou estudando programação a algumas semanas
- 🌱 Estou Aprendendo JavaScript,Html/CSS e um pouco de python
- 💞️ Estou aqui para aprender e me informar sobre o meio em que eu vou dedicar a minha vida
- 📫 Tenho curso basico em inglês,sou esforçado e aprendo rapido.
- ✨ Vocês vão me ver bastante por aqui!
